"""Initial_schema

Revision ID: b1dda54d7b09
Revises: 
Create Date: 2025-12-15 21:07:38.795586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1dda54d7b09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discord_messages', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('discord_messages', 'author_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('discord_messages', 'channel_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('discord_messages', 'guild_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('discord_messages', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_discord_author'), table_name='discord_messages')
    op.drop_index(op.f('idx_discord_created_at'), table_name='discord_messages')
    op.create_index(op.f('ix_discord_messages_created_at'), 'discord_messages', ['created_at'], unique=False)
    op.alter_column('wom_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('wom_records', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('wom_records', 'fetch_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('wom_snapshots', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('wom_snapshots', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('wom_snapshots', 'timestamp',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('wom_snapshots', 'ehp',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('wom_snapshots', 'ehb',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idx_wom_snapshots_user'), table_name='wom_snapshots')
    op.drop_index(op.f('idx_wom_snapshots_user_time'), table_name='wom_snapshots')
    op.create_index(op.f('ix_wom_snapshots_timestamp'), 'wom_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_wom_snapshots_username'), 'wom_snapshots', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wom_snapshots_username'), table_name='wom_snapshots')
    op.drop_index(op.f('ix_wom_snapshots_timestamp'), table_name='wom_snapshots')
    op.create_index(op.f('idx_wom_snapshots_user_time'), 'wom_snapshots', ['username', 'timestamp'], unique=False)
    op.create_index(op.f('idx_wom_snapshots_user'), 'wom_snapshots', ['username'], unique=False)
    op.alter_column('wom_snapshots', 'ehb',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('wom_snapshots', 'ehp',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('wom_snapshots', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('wom_snapshots', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('wom_snapshots', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('wom_records', 'fetch_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('wom_records', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('wom_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_discord_messages_created_at'), table_name='discord_messages')
    op.create_index(op.f('idx_discord_created_at'), 'discord_messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_discord_author'), 'discord_messages', ['author_name'], unique=False)
    op.alter_column('discord_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('discord_messages', 'guild_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('discord_messages', 'channel_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('discord_messages', 'author_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('discord_messages', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###
