# core/assets.py

# Mapping from Wise Old Man (or other API) Boss Names to local file names.
# Key: API/Display Name (Title Case usually)
# Value: Filename in assets/ folder
BOSS_ASSET_MAP = {
    "Abyssal Sire": "boss_abyssal_sire.png",
    "Alchemical Hydra": "boss_alchemical_hydra.png",
    "Barrows Chests": "boss_barrows_chests.png",
    "Bryophyta": "boss_bryophyta.png",
    "Callisto": "boss_callisto.png",
    "Cerberus": "boss_cerberus.png",
    "Chaos Elemental": "boss_chaos_elemental.png",
    "Chaos Fanatic": "boss_chaos_fanatic.png",
    "Commander Zilyana": "boss_commander_zilyana.png",
    "Corporeal Beast": "boss_corporeal_beast.png",
    "Crazy Archaeologist": "boss_crazy_archaeologist.png",
    "Dagannoth Prime": "boss_dagannoth_prime.png",
    "Dagannoth Rex": "boss_dagannoth_rex.png",
    "Dagannoth Supreme": "boss_dagannoth_supreme.png",
    "Deranged Archaeologist": "boss_deranged_archaeologist.png",
    "General Graardor": "boss_general_graardor.png",
    "Giant Mole": "boss_giant_mole.png",
    "Great Olm": "boss_great_olm.png",
    "Grotesque Guardians": "boss_grotesque_guardians.png",
    "Hespori": "boss_hespori.png",
    "K'ril Tsutsaroth": "boss_kril_tsutsaroth.png",
    "Kalphite Queen": "boss_kalphite_queen.png",
    "King Black Dragon": "boss_king_black_dragon.png",
    "Kraken": "boss_kraken.png",
    "Kree'arra": "boss_kreearra.png",
    "Mimic": "boss_mimic.png",
    "Nex": "boss_nex.png",
    "Obor": "boss_obor.png",
    "Phantom Muspah": "boss_phantom_muspah.png",
    "Sarachnis": "boss_sarachnis.png",
    "Scorpia": "boss_scorpia.png",
    "Skotizo": "boss_skotizo.png",
    "Tempoross": "boss_tempoross.png",
    "The Corrupted Gauntlet": "boss_the_corrupted_gauntlet.png",
    "The Gauntlet": "boss_the_gauntlet.png",
    "The Nightmare": "boss_the_nightmare.png",
    "Theatre Of Blood": "boss_theatre_of_blood.png",
    "Thermonuclear Smoke Devil": "boss_thermonuclear_smoke_devil.png",
    "TzKal-Zuk": "boss_tzkal-zuk.png",
    "TzTok-Jad": "boss_tztok-jad.png",
    "Venenatis": "boss_venenatis.png",
    "Verzik Vitur": "boss_verzik_vitur.png",
    "Vet'ion": "boss_vetion.png",
    "Vorkath": "boss_vorkath.png",
    "Wintertodt": "boss_wintertodt.png",
    "Zalcano": "boss_zalcano.png",
    "Zulrah": "boss_zulrah.png",
    "abyssal_sire": "boss_abyssal_sire.png",
    "alchemical_hydra": "boss_alchemical_hydra.png",
    "barrows_chests": "boss_barrows_chests.png",
    "bryophyta": "boss_bryophyta.png",
    "callisto": "boss_callisto.png",
    "cerberus": "boss_cerberus.png",
    "chaos_elemental": "boss_chaos_elemental.png",
    "chaos_fanatic": "boss_chaos_fanatic.png",
    "commander_zilyana": "boss_commander_zilyana.png",
    "corporeal_beast": "boss_corporeal_beast.png",
    "crazy_archaeologist": "boss_crazy_archaeologist.png",
    "dagannoth_prime": "boss_dagannoth_prime.png",
    "dagannoth_rex": "boss_dagannoth_rex.png",
    "dagannoth_supreme": "boss_dagannoth_supreme.png",
    "deranged_archaeologist": "boss_deranged_archaeologist.png",
    "general_graardor": "boss_general_graardor.png",
    "giant_mole": "boss_giant_mole.png",
    "great_olm": "boss_great_olm.png",
    "grotesque_guardians": "boss_grotesque_guardians.png",
    "hespori": "boss_hespori.png",
    "k'ril_tsutsaroth": "boss_kril_tsutsaroth.png",
    "kalphite_queen": "boss_kalphite_queen.png",
    "king_black_dragon": "boss_king_black_dragon.png",
    "kraken": "boss_kraken.png",
    "kree'arra": "boss_kreearra.png",
    "kreearra": "boss_kreearra.png",
    "kril_tsutsaroth": "boss_kril_tsutsaroth.png",
    "mimic": "boss_mimic.png",
    "nex": "boss_nex.png",
    "obor": "boss_obor.png",
    "phantom_muspah": "boss_phantom_muspah.png",
    "sarachnis": "boss_sarachnis.png",
    "scorpia": "boss_scorpia.png",
    "skotizo": "boss_skotizo.png",
    "tempoross": "boss_tempoross.png",
    "the_corrupted_gauntlet": "boss_the_corrupted_gauntlet.png",
    "the_gauntlet": "boss_the_gauntlet.png",
    "the_nightmare": "boss_the_nightmare.png",
    "theatre_of_blood": "boss_theatre_of_blood.png",
    "thermonuclear_smoke_devil": "boss_thermonuclear_smoke_devil.png",
    "tzkal-zuk": "boss_tzkal-zuk.png",
    "tztok-jad": "boss_tztok-jad.png",
    "venenatis": "boss_venenatis.png",
    "verzik_vitur": "boss_verzik_vitur.png",
    "vet'ion": "boss_vetion.png",
    "vetion": "boss_vetion.png",
    "vorkath": "boss_vorkath.png",
    "wintertodt": "boss_wintertodt.png",
    "zalcano": "boss_zalcano.png",
    "zulrah": "boss_zulrah.png",
    
    # NEW BOSSES (Snake Case for DB Lookup)
    "araxxor": "boss_araxxor.png",
    "artio": "boss_artio.png",
    "callisto_cub": "boss_callisto_cub.png",
    "calvarion": "boss_calvarion.png",
    "calvar'ion": "boss_calvar'ion.png",
    "duke_sucellus": "boss_duke_sucellus.png",
    "scurrius": "boss_scurrius.png",
    "shellbane_gryphon": "boss_shellbane_gryphon.png",
    "sol_heredit": "boss_sol_heredit.png",
    "spindel": "boss_spindel.png",
    "the_hueycoatl": "boss_the_hueycoatl.png",
    "the_leviathan": "boss_the_leviathan.png",
    "the_whisperer": "boss_the_whisperer.png",
    "vardorvis": "boss_vardorvis.png",
    "lunar_chests": "boss_lunar_chests.png",
    "amoxliatl": "boss_amoxliatl.png",
    "araxxor": "boss_araxxor.png",
    "artio": "boss_artio.png",
    "callisto_cub": "boss_callisto_cub.png",
    "calvarion": "boss_calvarion.png",
    "calvar'ion": "boss_calvar'ion.png",
    "duke_sucellus": "boss_duke_sucellus.png",
    "scurrius": "boss_scurrius.png",
    "shellbane_gryphon": "boss_shellbane_gryphon.png",
    "sol_heredit": "boss_sol_heredit.png"
}

# Fallback image if no match found
DEFAULT_BOSS_IMAGE = "boss_pet_rock.png"
